# Generated by Django 2.2 on 2021-04-12 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
        ('libros', '0002_auto_20210412_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autores', to='autores.Autor'),
        ),
    ]
