# Generated by Django 2.2 on 2021-04-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_libro_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autores',
        ),
    ]
